In [17]:
import numpy
numpy.loadtxt(fname='food_access_data.csv', delimiter=',')
#the error message says that I can't import my csv file as numpy because it's reading "1912" as a string
#I'm not sure why this happened since it's actually an integer, but I moved on based on the solution I saw on the forum

ValueError: could not convert string to float: '\ufeff1912'

In [21]:
import pandas as pd

In [22]:
tmp_data = pd.read_csv('food_access_data.csv')
#the past 2 commands import my csv file as pandas instead of numpy and names it "tmp_data"

In [23]:
data = tmp_data.to_numpy()
#this converts the temporary data "tmp_data" from pandas to numpy and names that "data"

In [24]:
print(data)
#I printed the data to make sure that it corresponds to my csv file
#It cut out the first row of data, but there is plenty more data here

[[2.170e+03 7.430e+02 1.820e+01 ... 5.000e+00 5.500e+01 7.500e+01]
 [3.373e+03 1.256e+03 1.910e+01 ... 1.100e+01 1.170e+02 8.700e+01]
 [4.386e+03 1.722e+03 3.300e+00 ... 1.100e+01 7.400e+01 8.500e+01]
 ...
 [2.542e+03 1.021e+03 1.270e+01 ... 2.600e+01 1.820e+02 4.070e+02]
 [3.314e+03 1.322e+03 9.200e+00 ... 4.700e+01 6.200e+01 9.100e+01]
 [3.894e+03 1.699e+03 1.500e+01 ... 4.400e+01 1.260e+02 1.250e+02]]


In [25]:
print(data[0:,0])
#this isolates the first column of the dataset (which corresponds to the population size) and prints it
#the first 0 corresponds to row 1, the : corresponds to the last row, and the second 0 corresponds to the first column

[2170. 3373. 4386. ... 2542. 3314. 3894.]


In [27]:
population_size = data[0:,0]
#this names the first column of my dataset "population_size" so that future analysis is easier

In [28]:
print(population_size)
#this prints the variable to make sure that the correct information is saved under this name

[2170. 3373. 4386. ... 2542. 3314. 3894.]


In [44]:
#the following commands name the remaining columns:
housing_unit = data[0:,1]
#Occupied housing unit count from 2010 census
poverty_rate = data[0:,2]
#Share of the tract population living with income at or below the Federal poverty thresholds for family size
white_half = data[0:,5]
#White population count beyond 1/2 mile from supermarket
black_half = data[0:,6]
#Black or African American population count beyond 1/2 mile from supermarket
asian_half = data[0:,7]
#Asian population count beyond 1/2 mile from supermarket
pac_isl_half = data[0:,8]
#Native Hawaiian or Other Pacific Islander population count beyond 1/2 mile from supermarket
nat_amer_half = data[0:,9]
#American Indian or Alaska Native population count beyond 1/2 mile from supermarket
other_half = data[0:,10]
#Other/Multiple race population count beyond 1/2 mile from supermarket
latino_half = data[0:,11]
#Hispanic or Latino ethnicity population count beyond 1/2 mile from supermarket

In [39]:
print(latino_half)
#spot-checking

[ 34.58790941  76.4086176   61.43777905 ... 146.8707357   76.88022638
  96.26057867]


In [45]:
#naming the next set of columns
white_1 = data[0:,15]
#White population count beyond 1 mile from supermarket
black_1 = data[0:,16]
#Black or African American population count beyond 1 mile from supermarket
asian_1 = data[0:,17]
#Asian population count beyond 1 mile from supermarket
pac_isl_1 = data[0:,18]
#Native Hawaiian or Other Pacific Islander population count beyond 1 mile from supermarket
nat_ame_1 = data[0:,19]
#American Indian or Alaska Native population count beyond 1 mile from supermarket
other_1 = data[0:,20]
#Other/Multiple race population count beyond 1 mile from supermarket
latino_1 = data[0:,21]
#Hispanic or Latino ethnicity population count beyond 1 mile from supermarket

In [41]:
print(latino_1)
#spot-checking

[11.17358974 31.22826762 29.85953993 ... 11.64341596 66.77413435
 69.21853762]


In [46]:
#naming the next set of variables
white_10 = data[0:,25]
#White population count beyond 10 miles from supermarket
black_10 = data[0:,26]
#Black or African American population count beyond 10 miles from supermarket
asian_10 = data[0:,27]
#Asian population count beyond 10 miles from supermarket
pac_isl_10 = data[0:,28]
#Native Hawaiian or Other Pacific Islander population count beyond 10 miles from supermarket
nat_ame_10 = data[0:,29]
#American Indian or Alaska Native population count beyond 10 miles from supermarket
other_10 = data[0:,30]
#Other/Multiple race population count beyond 10 miles from supermarket
latino_10 = data[0:,31]
#Hispanic or Latino ethnicity population count beyond 10 miles from supermarket
white_total = data[0:,34]
#Total count of White population in tract 
black_total = data[0:,35]
#Total count of Black or African American population in tract 
asian_total = data[0:,36]
#Total count of Asian population in tract
pac_isl_total = data[0:,37]
#Total count of Native Hawaiian and Other Pacific Islander population in tract
nat_ame_total = data[0:,38]
#Total count of American Indian and Alaska Native population in tract
other_total = data[0:,39]
#Total count of Other/Multiple race population in tract
latino_total = data[0:,40]
#Total count of Hispanic or Latino population in tract

In [47]:
print(latino_10)
print(latino_total)
#spot-checking

[ 0.          0.          0.         ...  0.         17.00000007
  0.        ]
[ 75.  87.  85. ... 407.  91. 125.]


In [60]:
numpy.average(white_half)
#calculate the average White population count beyond 1/2 mile from supermarket per census tract

2274.2177485265534

In [63]:
white_half_sum = numpy.sum(white_half)
#sum of White population count beyond 1/2 mile from supermarket named accordingly
print(white_half_sum)
white_total_sum = numpy.sum(white_total)
print(white_total_sum)

165706327.81089026
223551643.0


In [64]:
white_half_percent = white_half_sum/white_total_sum*100
print(white_half_percent)
#used python as a calculator
#percentage of white population that lives beyond 1/2 mile from supermarket

74.12440614936132


In [65]:
#can also calculate in this way:
numpy.sum(white_half)/numpy.sum(white_total)*100

74.12440614936132

In [66]:
black_half_percent = numpy.sum(black_half)/numpy.sum(black_total)*100
print(black_half_percent)
asian_half_percent = numpy.sum(asian_half)/numpy.sum(asian_total)*100
print(asian_half_percent)
pac_isl_half_percent = numpy.sum(pac_isl_half)/numpy.sum(pac_isl_total)*100
print(pac_isl_half_percent)
nat_ame_half_percent = numpy.sum(nat_ame_half)/numpy.sum(nat_ame_total)*100
print(nat_ame_half_percent)
other_half_percent = numpy.sum(other_half)/numpy.sum(other_total)*100
print(other_half_percent)
latino_half_percent = numpy.sum(latino_half)/numpy.sum(latino_total)*100
print(latino_half_percent)

62.60465100795061
54.04495715568467
61.07425688760808
73.63924134804552
55.182529892345144
54.90252374672336


In [68]:
white_10_percent = numpy.sum(white_10)/numpy.sum(white_total)*100
print(white_10_percent)
black_10_percent = numpy.sum(black_10)/numpy.sum(black_total)*100
print(black_10_percent)
asian_10_percent = numpy.sum(asian_10)/numpy.sum(asian_total)*100
print(asian_10_percent)
pac_isl_10_percent = numpy.sum(pac_isl_10)/numpy.sum(pac_isl_total)*100
print(pac_isl_10_percent)
nat_ame_10_percent = numpy.sum(nat_ame_10)/numpy.sum(nat_ame_total)*100
print(nat_ame_10_percent)
other_10_percent = numpy.sum(other_10)/numpy.sum(other_total)*100
print(other_10_percent)
latino_10_percent = numpy.sum(latino_10)/numpy.sum(latino_total)*100
print(latino_10_percent)

1.9291879670927565
0.8718103068396604
0.15660041866430163
0.9084163444392266
11.54638916089467
0.8525437845488179
0.7738845687701836


In [71]:
numpy.max(white_half)
#this gives me the maximum value for the White population count beyond 1/2 mile from supermarket

28477.0001

In [72]:
numpy.min(white_half)
#this gives me the minimum value for the White population count beyond 1/2 mile from supermarket

0.0

In [73]:
numpy.std(white_half)
#this gives me the standard deviation for the White population count beyond 1/2 mile from supermarket

1820.942381338809